name: transformer_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - tensorboard
  - tqdm
  - pip
  - pip:
    - datasets
    - tokenizers
